apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: home
spec:
  hosts: ["app.thindexed.personal.shoot.canary.k8s-hana.ondemand.com"]
  gateways: [ "gateway-app" ]
  http:
    - match:
      - uri:
          exact: "/home"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: home



